baseURL = "https://anddt.com"
title = "Andrea Dodet"
theme = "cactus"
copyright = "Andrea dodet"

languageCode = "en-gb"
hasCJKLanguage = true

enableRobotsTXT = true

# Google Analytics
googleAnalytics = "UA-58930119-2"

[params]
colortheme = "white"  # default: auto. light: light theme, dark: dark theme, auto: based on system.
logo = "logo.png"  # if you have a logo png
description = "Jotting down things I'd like to understand"
showAllPostsOnHomePage = true
postOnHomePage = 15
license = ""  # CC License
rss = true
css = ["css/custom.css"]

[[menu.main]]
name = "Writings"
url = "/post"
weight = 1

[params.comments]
enabled = true
engine = 'disqus'
disqusShortname = "anddt-com"

[[params.social]]
name = 'github'
link = 'https://github.com/andodet'

[[params.social]]
name = 'twitter'
link = 'https://twitter.com/andodet'

[[params.social]]
name = 'linkedin'
link = 'https://www.linkedin.com/in/andodet/?locale=en_US'

[params.math]
enable = false  # optional: true, false. Enable globally, default: false. You can always enable math on per page.
use = "katex"  # option: "katex", "mathjax". default: "katex"

[markup]
[markup.highlight]
codefences = true
codeFences = true
guessSyntax = true
hl_Lines = ""
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
style = "rrt"
tabWidth = 4

