baseURL = "https://anddt.com"
title = "Andrea Dodet"
theme = "hugo-notepadium"
copyright = "2020 Andrea dodet"

languageCode = "en-gb"
hasCJKLanguage = true

enableRobotsTXT = true

# Enable Disqus
disqusShortname = "andreadodet"

# Google Analytics
googleAnalytics = "UA-58930119-2"

[markup.highlight]
codeFences = true
noClasses = false

[markup.goldmark.renderer]
unsafe = true  # enable raw HTML in Markdown

[params]
style = "auto   "  # default: auto. light: light theme, dark: dark theme, auto: based on system.
dateFormat = "Monday, January 2, 2006"  # if unset, default is "2006-01-02"
logo = "logo.png"  # if you have a logo png
slogan = "Jotting down things I'd like to understand"
license = ""  # CC License

[params.comments]
enable = false  # En/Disable comments globally, default: false. You can always enable comments on per page.

[params.math]
enable = false  # optional: true, false. Enable globally, default: false. You can always enable math on per page.
use = "katex"  # option: "katex", "mathjax". default: "katex"

[params.syntax]
use = "none"  # builtin: "prismjs", "hljs". "none" means Chroma
theme = "xcode"
darkTheme = "monokai"  # apply this theme in dark mode

[params.nav]
showCategories = true       # /categories/
showTags = false            # /tags/

# custom navigation items
[[params.nav.custom]]
#title = "About"
#url = "/about"
